expr_group: magent
expr_name: marl_dqn_vs_attack
log_dir: logs
log_name: 'Marl'
seed: 123
eval_only: False

distributed:
  use: False
  auto_connect:
  auto_copy:
  nodes:
    master:
      ip: 'auto'
    workers:      
      - ip:

framework:
  name: "psro"                # framework name
  max_rounds: 1         # psro rounds
  meta_solver: "nash"         # 'nash', 'uniform', 'pfsp'
  sync_training: True
  on_policy: False
  stopper:
    type: "win_rate_stopper"
    kwargs:
      min_win_rate: 1.1
      max_steps: 50000          #iteration at each psro round


agent_manager:
  num_agents: 2
#  agent_ids: ['red']
  share_policies: False

evaluation_manager:
  num_eval_rollouts: 20

policy_data_manager:
  update_func: "gym"
  fields:
    payoff:
      type: "matrix"
      missing_value: -100 
    score:
      type: "matrix"
      missing_value: -100 
    win:
      type: "matrix"
      missing_value: -100 
    lose:
      type: "matrix"
      missing_value: -100 
    reward:
      type: "matrix"
      missing_value: -100
    exploitability:
      type: "array"
      missing_value: -100
        
monitor:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]

# TODO
league:
  role: "client"
  server_ip: ""
  server_port: ""

rollout_manager:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]
  num_workers: 5
  seed: 12345
  saving_interval: 10000 # the sequence of dump model's weight
  batch_size: ${rollout_manager.num_workers}
  eval_batch_size: 100
  eval_freq: 50 # epochs
  min_samples: ${training_manager.batch_size}
  rollout_metric_cfgs:
    reward:
      type: "sliding"
      window_size: 20
      init_list: [-10000]
    win:
      type: "sliding"
      window_size: 20
      init_list: [0,0,0,0,0]
  worker:
    distributed:
      resources:
        num_cpus: 1
    rollout_length: 200
    eval_rollout_length: 200
    sample_length: 200
    padding_length: # of not use in gr_football
    rollout_func_name: "rollout_func_magent"
    episode_mode: 'time-step'
    credit_reassign:
#    rollout_func_cfg:
#      episode_mode: "time-step"    #traj: whole trajectory (for PPO) and time-step
    mix_opponent: False
    envs:
      - cls: "magent"
        id_prefix: "magent"
        env_id: "battle_v3"
        map_size: 15
        max_cycles: 500
        global_encoder: false


training_manager:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]
 
  master_addr: "127.0.0.1"
  master_port:  #"12774"
  local_queue_size: 1
  batch_size: 256 # how many data sample from DatasetServer per time.
  num_prefetchers: 1
  data_prefetcher:
    distributed:
      resources:
        num_cpus: 1
  num_trainers: 1
  # control the frequency of remote parameter update
  update_interval: 1
  gpu_preload: False
  trainer:
    distributed:
      resources:
        num_cpus: 1
        num_gpus: 1
        resources:
          - ["node:${distributed.nodes.master.ip}",0.01]
    optimizer: "Adam"
    actor_lr: 1e-3
    critic_lr: 1e-3
    opti_eps: 1.e-5
    weight_decay: 0.05
    lr_decay: False            #update_linear_schedule
    lr_decay_epoch: 2000      #how many rollout steps till zero

data_server:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]
  table_cfg:
    capacity: 10000
    sampler_type: "uniform"
    sample_max_usage: 1000 # this might also be problematic when sync training...
    rate_limiter_cfg:
      min_size: ${training_manager.batch_size}
      # r_w_ratio: 10.0 # cannot set it if sync training...
  read_timeout: 120

policy_server:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]

populations:
  - population_id: 'default' # population_id
    agent_group: "agent_0"
    algorithm:
      name: "DQN"
      model_config:
        model: "magent.dqn"
        initialization:
          use_orthogonal: True
          gain: 1.
        actor:
          network: mlp
          layers:
            - units: 64
              activation: ReLU
            - units: 32
              activation: ReLU
          output:
            activation: False
        critic:
          network: mlp
          layers:
            - units: 64
              activation: ReLU
            - units: 32
              activation: ReLU
          output:
            activation: False

      # set hyper parameter
      custom_config:
        explore_cfg:
          mode: "epsilon_greedy"
          # epsilon: 0.5
          max_epsilon: 0.5
          min_epsilon: 0.1
          total_decay_steps: ${framework.stopper.kwargs.max_steps}

        gamma: 0.99
        use_cuda: False  # enable cuda or not
        use_q_head: False
        epoch: 1
        num_mini_batch: 1  # the number of mini-batches
        max_grad_norm: 0.5
        
        return_mode: new_gae
        gae:
          gae_lambda: 0.95
        vtrace:
          clip_rho_threshold: 1.0
          clip_pg_rho_threshold: 100.0

        use_rnn: False
        # this is not used, instead it is fixed to last hidden in actor/critic
        rnn_layer_num: 1
        rnn_data_chunk_length: 16

        use_feature_normalization: True
        use_popart: False
        popart_beta: 0.99999

        entropy_coef: 0.00
        clip_param: 0.2

        use_modified_mappo: False

        target_update_freq: 200
        target_update_lr: 0.5

      policy_init_cfg:
        agent_0: # agent_id
          new_policy_ctr_start: -1
          init_cfg:
            - condition: "==0" # condition if True in order
              strategy: random # now support pretrained, inherit_last, random
              policy_id:
              policy_dir:
          initial_policies:

        agent_1:
          new_policy_ctr_start: -1
          init_cfg:
            - condition: "==0" # condition if True in order
              strategy: pretrained # now support pretrained, inherit_last, random
              policy_id: attack_rule
              policy_dir: light_malib/trained_models/magent/attack_rule
          initial_policies:                         #initial population